# fish completion for vedi

complete -c vedi -s S -l no-wrap -d 'Do not wrap long lines'
complete -c vedi -l wrap -d 'Wrap long lines'
complete -c vedi -l wrap-style -x -a 'char word' -d 'Wrap at the screen\'s edge or at words'
complete -c vedi -s F -l quit-if-one-page -d 'Print the text and quit if it fits the screen'
complete -c vedi -l no-quit-if-one-page -d 'Page text that fits the screen'
complete -c vedi -l one-page-rows-below -x -d 'Rows -F leaves below the text, for the prompt'
complete -c vedi -l auto-reload -d 'Read a file again when it changes on disk'
complete -c vedi -l no-auto-reload -d 'Do not read a changed file again'
complete -c vedi -l scrolled-by -x -d 'Start on the last screenful, scrolled N rows up'
complete -c vedi -l cursor-row -x -d 'Put the cursor on row N of the last screenful'
complete -c vedi -l cursor-col -x -d 'Put the cursor in column N of the last screenful'
complete -c vedi -l clipboard-cmd -x -a '(__fish_complete_command)' -d 'Pipe copied text to a command instead of OSC 52'
complete -c vedi -l no-clipboard-cmd -d 'Copy with OSC 52, or pbcopy in Terminal.app'
complete -c vedi -l open-cmd -x -a '(__fish_complete_command)' -d 'Read each file by running a command, %s the file'
complete -c vedi -l no-open-cmd -d 'Read each file as it is'
complete -c vedi -l tab-width -x -d 'Draw a tab as N cells'
complete -c vedi -l edge-markers -d 'Mark text off the sides and wrapped rows'
complete -c vedi -l no-edge-markers -d 'Do not mark text off the sides or wrapped rows'
complete -c vedi -l file-separators -d 'With several inputs, draw a row naming each'
complete -c vedi -l no-file-separators -d 'Draw no row naming each input'
complete -c vedi -l status-line -d 'Draw the status line'
complete -c vedi -l no-status-line -d 'Draw the status line only for a prompt or a message'
complete -c vedi -l view-style -x -a 'color plain raw' -d 'Draw the text in color, plain or with its escapes as text'
complete -c vedi -l config -r -F -d 'Read the config from a file'
complete -c vedi -l completion -x -a 'bash zsh fish' -d 'Print the completion script for a shell'
complete -c vedi -s h -l help -d 'Show the help'
complete -c vedi -s v -l version -d 'Print the version'
